### ISSUE TITLE
Question RE: Web Address Creation

### ISSUE THREAD

**Issue by stinkins** [jlacko/gmapsdistance#1]
When the API call is used for this package, what is the created web address? I seem to be having issues with the API call failing. However, when I build the web address and use a different browser, it passes and gives results.

Thanks.

**Comment by jlacko** [comment]
Could you share your actual call? without your api key ofc.? 

I am always grateful for cruel & unusual call combinations "from the wild" as they help with unit testing.

The actual call is constructed on https://github.com/jlacko/gmapsdistance/blob/master/R/gmapsdistance.R#L349

**Comment by stinkins** [comment]
Here is the code we are using:

adv_distances<- gmapsdistance(origin=advadd$fullrpadd,
                              destination=advadd$fulladvadd,
                              mode="driving",
                              key=mykey,
                              combinations="pairwise")

The data for the two variables are set up as addresses with + dividers. I actually built a sample URL from your documentation and it gave me return data.  I am getting this error: Google API call failed; check your internet connection. It seems this may be internal problem for me but I wanted to see how the API calls were constructed to confirm this thought.

**Comment by jlacko** [comment]
hm... it does seem as if this really was related to your particular installation - I have a test case for pairwise 
distances implemented, and it passes on both linux and windows / see https://github.com/jlacko/gmapsdistance/blob/master/tests/testthat/test-3-matrix.R#L42

You may consider removing the plus connectors; these used to be required prior to version 4.0.0 (April this year) but are no longer necessary. 

This is a side effect of introducing URL encoding via `utils::URLencode()` in order to properly handle non-ASCII characters.

**Comment by jlacko** [comment]
On second thought... there seems to be something funny going on.

When I run

```
gmapsdistance(
    origin = c("Washington DC", "Miami FL", "Seattle WA"),
    destination = c("Washington DC", "Miami FL", "Seattle WA"),
    key = Sys.getenv("GOOGLE_API_KEY"),
    mode = "driving",
    combinations = "pairwise"
  )
```
I get a result which passes the formal tests, but does not quite make sense:

```
$Distance
             or            de Distance
1 Washington DC Washington DC        0
2      Miami FL      Miami FL        0
3    Seattle WA    Seattle WA        0

$Time
             or            de Time
1 Washington DC Washington DC    0
2      Miami FL      Miami FL    0
3    Seattle WA    Seattle WA    0

$Status
             or            de status
1 Washington DC Washington DC     OK
2      Miami FL      Miami FL     OK
3    Seattle WA    Seattle WA     OK
```

Note the zero distances and travel times. I will need to investigate :(

**Comment by stinkins** [comment]
I reviewed the last two comments you made. I have done the following with no change to my results:

1. Removed the + in the strings defining my address.
2. Removed the driving mode (since it defaults).
3. Moving my key from a separate variable into the gmapsdistance function with a Sys.getenv call.
4. Removed the pairwise combinations.

I am currently working with my tech team to see if this is an issue with our internal servers blocking these calls but we shall see. I appreciate your help today.

**Comment by jlacko** [comment]
Oki, thanks for letting me know! 

I would be happy to check a sample of your data - a pair or two of locations, whatever - to see if your error reproduces. As I mentioned I am grateful for reproducible errorrs, as they drive the package forward.

Also double check your encoding - if you are using non-ASCII place names you need to make sure they are in UTF-8. This may not be the default, especially when on Windows.

**Comment by stinkins** [comment]
Here are some samples. I  am currently only using the full address for 1 side of the query. Also, I don't have the query update to remove the + as I had previously. I am also trying it to if changing from the full address on the origin side makes a difference (which it did not).

**Origins:**
126+Wells+Ave+S+Renton+Washington+State+98057-2152
6650+SW+Redwood+Ln+Ste+160+Portland+Oregon+97224-7184

**Destinations:**
West+Linn+Oregon+97068-9502
San+Mateo+California+94403-1332

**Comment by jlacko** [comment]
I can confirm that I am unable to reproduce the error based on your two origin / destination pairs = the issue is on your side.

```
> library(gmapsdistance)
>  gmapsdistance(
+     origin = c("126+Wells+Ave+S+Renton+Washington+State+98057-2152",
+                "6650+SW+Redwood+Ln+Ste+160+Portland+Oregon+97224-7184"),
+     destination = c("West+Linn+Oregon+97068-9502",
+                     "San+Mateo+California+94403-1332"),
+     key = Sys.getenv("GOOGLE_API_KEY"),
+     mode = "driving",
+     combinations = "pairwise"
+   )
$Distance
                                                     or                              de Distance
1    126+Wells+Ave+S+Renton+Washington+State+98057-2152     West+Linn+Oregon+97068-9502   290720
2 6650+SW+Redwood+Ln+Ste+160+Portland+Oregon+97224-7184 San+Mateo+California+94403-1332  1038552

$Time
                                                     or                              de  Time
1    126+Wells+Ave+S+Renton+Washington+State+98057-2152     West+Linn+Oregon+97068-9502 10658
2 6650+SW+Redwood+Ln+Ste+160+Portland+Oregon+97224-7184 San+Mateo+California+94403-1332 36519

$Status
                                                     or                              de status
1    126+Wells+Ave+S+Renton+Washington+State+98057-2152     West+Linn+Oregon+97068-9502     OK
2 6650+SW+Redwood+Ln+Ste+160+Portland+Oregon+97224-7184 San+Mateo+California+94403-1332     OK
```
I will update the package's unit tests just in case - I like how your call includes ZIP codes - but there seems little I can do for you  on my side.

**Comment by stinkins** [comment]
Yes, I also can confirm the error is on my end. Working with my tech team to disable our internet security allowed the query to work.
